# Kong Declarative Configuration
# API Gateway routing and plugin configuration

_format_version: "3.0"
_transform: true

# ==========================================================================
# Services - Backend microservices
# ==========================================================================

services:
  - name: catalog-service
    url: http://catalog-service:5001
    protocol: http
    connect_timeout: 60000
    write_timeout: 60000
    read_timeout: 60000
    retries: 3
    routes:
      - name: catalog-products
        paths:
          - /api/v1/products
          - /api/v1/categories
          - /api/v1/search
        strip_path: false
        methods:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE

  - name: cart-service
    url: http://cart-service:5002
    routes:
      - name: cart-operations
        paths:
          - /api/v1/cart
        strip_path: false
        methods:
          - GET
          - POST
          - PUT
          - DELETE

  - name: checkout-service
    url: http://checkout-service:5003
    routes:
      - name: checkout-flow
        paths:
          - /api/v1/checkout
        strip_path: false
        methods:
          - POST
          - GET

  - name: payment-service
    url: http://payment-service:5004
    routes:
      - name: payment-processing
        paths:
          - /api/v1/payments
        strip_path: false
        methods:
          - POST
          - GET

  - name: inventory-service
    url: http://inventory-service:5005
    routes:
      - name: inventory-check
        paths:
          - /api/v1/inventory
        strip_path: false
        methods:
          - GET
          - POST

  - name: orders-service
    url: http://orders-service:5006
    routes:
      - name: order-management
        paths:
          - /api/v1/orders
        strip_path: false
        methods:
          - GET
          - POST
          - PUT

  - name: accounts-service
    url: http://accounts-service:5008
    routes:
      - name: user-accounts
        paths:
          - /api/v1/users
          - /api/v1/auth
        strip_path: false
        methods:
          - GET
          - POST
          - PUT
          - DELETE

  - name: recommendations-service
    url: http://recommendations-service:5009
    routes:
      - name: product-recommendations
        paths:
          - /api/v1/recommendations
        strip_path: false
        methods:
          - GET

# ==========================================================================
# Global Plugins
# ==========================================================================

plugins:
  # Rate limiting - prevent abuse
  - name: rate-limiting
    config:
      minute: 100
      hour: 5000
      policy: redis
      redis_host: redis
      redis_port: 6379
      redis_password: dev_password
      fault_tolerant: true
      hide_client_headers: false

  # CORS - enable cross-origin requests
  - name: cors
    config:
      origins:
        - http://localhost:3000
        - http://localhost:3001
        - https://ecommerce-platform.com
      methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
      headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - Authorization
        - X-Correlation-ID
        - X-Request-ID
      exposed_headers:
        - X-Correlation-ID
        - X-RateLimit-Limit
        - X-RateLimit-Remaining
      credentials: true
      max_age: 3600
      preflight_continue: false

  # Request/Response logging
  - name: file-log
    config:
      path: /var/log/kong/access.log
      reopen: true

  # Prometheus metrics
  - name: prometheus
    config:
      per_consumer: false

  # Request ID
  - name: correlation-id
    config:
      header_name: X-Correlation-ID
      generator: uuid
      echo_downstream: true

  # IP restriction (optional - for admin routes)
  # - name: ip-restriction
  #   route: admin-routes
  #   config:
  #     allow:
  #       - 10.0.0.0/8
  #       - 172.16.0.0/12
  #       - 192.168.0.0/16

# ==========================================================================
# Upstreams - Load balancing configuration
# ==========================================================================

upstreams:
  - name: catalog-upstream
    algorithm: round-robin
    hash_on: none
    hash_fallback: none
    healthchecks:
      active:
        type: http
        http_path: /health
        timeout: 1
        concurrency: 10
        healthy:
          interval: 5
          successes: 2
        unhealthy:
          interval: 5
          http_failures: 3
          timeouts: 2
      passive:
        healthy:
          successes: 5
        unhealthy:
          http_failures: 5
          timeouts: 3
    targets:
      - target: catalog-service:5001
        weight: 100
